# Generated by Django 5.2 on 2025-04-19 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=50)),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('team', models.CharField(max_length=50)),
                ('case_type', models.CharField(max_length=50)),
                ('case_status', models.CharField(max_length=50)),
                ('case_description', models.TextField(blank=True, null=True)),
                ('case_start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Laptop', 'Laptop'), ('Smartphone', 'Smartphone'), ('Tablet', 'Tablet'), ('USB Drive', 'USB Drive'), ('External HDD', 'External HDD'), ('External SSD', 'External SSD'), ('Digital Camera', 'Digital Camera'), ('Smartwatch', 'Smartwatch'), ('Router', 'Router'), ('Server', 'Server'), ('Network Device', 'Network Device'), ('IoT Device', 'IoT Device'), ('Cloud Storage', 'Cloud Storage'), ('Drone', 'Drone'), ('Wearable Device', 'Wearable Device'), ('Backup Device', 'Backup Device'), ('Smart Home Device', 'Smart Home Device'), ('Smart TV', 'Smart TV'), ('Game Console', 'Game Console'), ('Other', 'Other')], max_length=50)),
                ('evidence_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('imei', models.CharField(blank=True, max_length=16, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('book_date', models.DateField(blank=True, null=True)),
                ('storage_location', models.CharField(choices=[('Inbeslag', 'Inbeslag'), ('Digi', 'Digi'), ('Rst', 'Rst'), ('See journal', 'See journal'), ('other', 'other')], max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('In Storage', 'In Storage'), ('Under Analysis', 'Under Analysis'), ('Analyzed', 'Analyzed'), ('Returned', 'Returned'), ('Destroyed', 'Destroyed'), ('Lost', 'Lost'), ('Stolen', 'Stolen'), ('Other', 'Other'), ('Pending', 'Pending'), ('Archived', 'Archived'), ('In Transit', 'In Transit'), ('Awaiting Approval', 'Awaiting Approval'), ('Pending Disposal', 'Pending Disposal'), ('Pending Return', 'Pending Return'), ('Pending Analysis', 'Pending Analysis'), ('Pending Review', 'Pending Review'), ('Pending Collection', 'Pending Collection'), ('Pending Transfer', 'Pending Transfer'), ('Pending Destruction', 'Pending Destruction'), ('Pending Investigation', 'Pending Investigation'), ('Pending Confirmation', 'Pending Confirmation'), ('Pending Documentation', 'Pending Documentation'), ('Pending Verification', 'Pending Verification'), ('Pending Assessment', 'Pending Assessment'), ('Pending Approval', 'Pending Approval'), ('Pending Closure', 'Pending Closure'), ('Pending Release', 'Pending Release'), ('Pending Follow-up', 'Pending Follow-up'), ('Pending Coordination', 'Pending Coordination'), ('Pending Communication', 'Pending Communication'), ('Pending Review and Analysis', 'Pending Review and Analysis')], default='Pending', max_length=50)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='api.case')),
            ],
        ),
    ]
