# Generated by Django 5.2 on 2025-04-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Archived', 'Archived'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Open', max_length=50),
        ),
    ]
