# Generated by Django 5.2 on 2025-04-23 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_case_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='acquisition_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='acquisition_method',
            field=models.CharField(choices=[('GaryKey', 'Garykey'), ('Cellebrite', 'Cellebrite'), ('Other', 'Other')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
