# Generated by Django 5.2 on 2025-04-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_items_acquisition_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='evidence_pictures/'),
        ),
    ]
